### ISSUE TITLE
[Bug]: Sigil doesn't build with Python 3.11

### ISSUE THREAD

**Issue by 0-wiz-0** [Sigil-Ebook/Sigil#703]
### Bug Description

When building Sigil 1.9.20 against Python 3.11.0, the build fails in EmbedPython with:
```
In file included from /scratch/editors/Sigil/work/.buildlink/include/python3.11/Python.h:38,
                 from /scratch/editors/Sigil/work/Sigil-1.9.20/src/EmbedPython/EmbeddedPython.h:27,
                 from /scratch/editors/Sigil/work/Sigil-1.9.20/src/EmbedPython/EmbeddedPython.cpp:23:
/scratch/editors/Sigil/work/.buildlink/include/python3.11/pyport.h:19:39: error: expected '(' before 'static_cast'
   19 | #  define _Py_STATIC_CAST(type, expr) static_cast<type>(expr)
      |                                       ^~~~~~~~~~~
/scratch/editors/Sigil/work/.buildlink/include/python3.11/cpython/unicodeobject.h:351:34: note: in expansion of macro '_Py_STATIC_CAST'
  351 | #define PyUnicode_1BYTE_DATA(op) _Py_STATIC_CAST(Py_UCS1*, PyUnicode_DATA(op))
      |                                  ^~~~~~~~~~~~~~~
/scratch/editors/Sigil/work/Sigil-1.9.20/src/EmbedPython/EmbeddedPython.cpp:483:78: note: in expansion of macro 'PyUnicode_1BYTE_DATA'
  483 |             res = QVariant(QString::fromLatin1(reinterpret_cast<const char *>PyUnicode_1BYTE_DATA(po), -1));
      |                                                                              ^~~~~~~~~~~~~~~~~~~~
/scratch/editors/Sigil/work/Sigil-1.9.20/src/EmbedPython/EmbeddedPython.cpp:483:108: error: expected ')' before ';' token
  483 |             res = QVariant(QString::fromLatin1(reinterpret_cast<const char *>PyUnicode_1BYTE_DATA(po), -1));
      |                           ~                                                                                ^
      |                                                                                                            )
```

This simple change (adding parentheses) fixes it for me:

```
--- src/EmbedPython/EmbeddedPython.cpp.orig     2022-08-31 15:13:03.000000000 +0000
+++ src/EmbedPython/EmbeddedPython.cpp
@@ -480,7 +480,7 @@ QVariant EmbeddedPython::PyObjectToQVari

         if (kind == PyUnicode_1BYTE_KIND) {
             // latin 1 according to PEP 393
-            res = QVariant(QString::fromLatin1(reinterpret_cast<const char *>PyUnicode_1BYTE_DATA(po), -1));
+            res = QVariant(QString::fromLatin1(reinterpret_cast<const char *>(PyUnicode_1BYTE_DATA(po), -1)));

         } else if (kind == PyUnicode_2BYTE_KIND) {
 #if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
```

### Platform (OS)

other

### OS Version / Specifics

NetBSD/amd64/pkgsrc

### What version of Sigil are you using?

1.9.20

**Comment by kevinhendricks** [comment]
Closing as already fixed in master with this merged pull request.
https://github.com/Sigil-Ebook/Sigil/pull/699
