### ISSUE TITLE
[Bug]: Sigil fails to build with Qt6 6.8.0: `qchar.h:66:2: error: This macro has been removed in Qt 6.8`

### ISSUE THREAD

**Issue by barracuda156** [Sigil-Ebook/Sigil#784]
### Bug Description

Sigil does not build with Qt6 6.8.0.

### Platform (OS)

macOS

### OS Version / Specifics

14.7.1

### What version of Sigil are you using?

2.3.1

### Any backtraces or crash reports

```shell
[ 32%] Building CXX object src/CMakeFiles/Sigil.dir/Tabs/TextTab.cpp.o
cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src && /opt/local/bin/ccache /usr/bin/clang++ -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_IMPLICIT_QCHAR_CONSTRUCTION -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_WEBCHANNEL_LIB -DQT_WEBENGINECORE_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src/Sigil_autogen/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/internal/gumbo -I/opt/local/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -I/opt/local/include -I/opt/local/include/minizip -I/opt/local/include/hunspell -isystem /opt/local/libexec/qt6/lib/QtWidgets.framework/Headers -iframework /opt/local/libexec/qt6/lib -isystem /opt/local/libexec/qt6/lib/QtCore.framework/Headers -isystem /opt/local/libexec/qt6/mkspecs/macx-clang -isystem /opt/local/libexec/qt6/include -isystem /opt/local/libexec/qt6/lib/QtGui.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtXml.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtPrintSupport.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtWebEngineCore.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtNetwork.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtQuick.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtQml.framework/Headers -isystem /opt/local/libexec/qt6/include/QtQmlIntegration -isystem /opt/local/libexec/qt6/lib/QtQmlMeta.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtQmlModels.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtQmlWorkerScript.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtOpenGL.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtWebChannel.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtPositioning.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtWebEngineWidgets.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtConcurrent.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtSvg.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtUiTools.framework/Headers -isystem /opt/local/libexec/qt6/lib/QtOpenGLWidgets.framework/Headers -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -mmacosx-version-min=14.0 -MD -MT src/CMakeFiles/Sigil.dir/Tabs/TextTab.cpp.o -MF CMakeFiles/Sigil.dir/Tabs/TextTab.cpp.o.d -o CMakeFiles/Sigil.dir/Tabs/TextTab.cpp.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/TextTab.cpp
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/sigil_constants.cpp:24:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/QString:1:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/TextTab.cpp:23:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/QTimer:1:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qtimer.h:12:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qobject.h:11:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/ContentTab.cpp:23:
In file included from /opt/local/libexec/qt6/lib/QtWidgets.framework/Headers/QLayout:1:
In file included from /opt/local/libexec/qt6/lib/QtWidgets.framework/Headers/qlayout.h:8:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qobject.h:11:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/TabBar.cpp:25:
In file included from /opt/local/libexec/qt6/lib/QtGui.framework/Headers/QContextMenuEvent:1:
In file included from /opt/local/libexec/qt6/lib/QtGui.framework/Headers/qevent.h:14:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qiodevice.h:10:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qobject.h:11:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/TabManager.cpp:23:
In file included from /opt/local/libexec/qt6/lib/QtGui.framework/Headers/QPalette:1:
In file included from /opt/local/libexec/qt6/lib/QtGui.framework/Headers/qpalette.h:9:
In file included from /opt/local/libexec/qt6/lib/QtGui.framework/Headers/qcolor.h:10:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstringlist.h:5:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qlist.h:10:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qhashfunctions.h:9:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/Tabs/FlowTab.cpp:26:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/QTimer:1:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qtimer.h:12:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qobject.h:11:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/sigil_constants.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src/Sigil_autogen/mocs_compilation.cpp:2:
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src/Sigil_autogen/BQTXKM6SMT/moc_Book.cpp:9:
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build/src/Sigil_autogen/BQTXKM6SMT/../../../../Sigil-2.3.1/src/BookManipulation/Book.h:27:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/QHash:1:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qhash.h:10:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qhashfunctions.h:9:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/main.cpp:24:
In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/Sigil-2.3.1/src/EmbedPython/EmbeddedPython.h:28:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/QCoreApplication:1:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qcoreapplication.h:8:
In file included from /opt/local/libexec/qt6/lib/QtCore.framework/Headers/qstring.h:14:
/opt/local/libexec/qt6/lib/QtCore.framework/Headers/qchar.h:66:2: error: This macro has been removed in Qt 6.8.
#error This macro has been removed in Qt 6.8.
 ^
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Tabs/TabBar.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Tabs/ContentTab.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Tabs/TextTab.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Tabs/TabManager.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Tabs/FlowTab.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/main.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/Sigil.dir/Sigil_autogen/mocs_compilation.cpp.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_sigil/sigil/work/build'
make[1]: *** [src/CMakeFiles/Sigil.dir/all] Error 2
```
```

**Comment by barracuda156** [comment]
> Closing as already fixed in master.

Thank you. Could you make a new tag though which includes the fix?

**Comment by kevinhendricks** [comment]
Why ... master  is buildable now.  Perhaps just cherry pick the commit.  I will look it up.

**Comment by barracuda156** [comment]
@kevinhendricks Thanks, I will refer the PR with a fix in Trac ticket. (Sigil broken in MacPorts now due to this issue.)

**Comment by barracuda156** [comment]
UPD. Just to confirm, the patch from the referred PR fixes the build of Sigil.
